### ISSUE TITLE
Instance creation process UI idea

### ISSUE THREAD

**Issue by vevmesteren** [StudioQi/jeto#46]
Creating a new machine in Jeto is a breeze. 
A nifty little feature when in the "Create a new machine" form, would be to add a checkbox next to the "Create" Button that not only creates the machine, but takes me to the next screen and starts the vagrant up / provision process. 
Either a checkbox, or a second button "Create & Start". UX skills anyone?

**Comment by PierrePaul** [comment]
I've limited the scope if this issue to : when creating a new instance, get redirected directly to the new instance.

This is what 99% of the people want. I didnt include the checkbox to auto-start/provision the instance because, in most case, Jeto needs to either download an archive for the project, or clone the project from git. This step takes time and I want to make sure the interface comes back as quickly as possible from this. Thanks for this issue, it's a great step forward in usability.

**Comment by vevmesteren** [comment]
Works for me
☺
